### ISSUE TITLE
ipv6 Big in AllPro 4.7

### ISSUE THREAD

**Issue by fahadmehar** [sirfz/allprotection#1]
There is an ipv6 Bugg for ver 4.7 (ipv6 eggdrops. ) We have to disable (Anti-Spam) before we load the TCL in eggdrop, otherwise TCL won't work... and also change control codes for kick messages... about flood. 
It's -Rm -R channel during flood. It should lock the channel for some certn time for flood to stop.
there are many miner bugs like this... I quote big issues... which not only me but everyone is facing... but they don't know how to contact the TCL owner. Please look into these issues.  Thanks

-Fahad

**Comment by sirfz** [comment]
Hi Fahed,

Thanks for your report. Could you please open a separate issue for each of the issues you're talking about with details?

Details should include error messages if they exist and expected behavior vs actual behavior.

**Comment by fahadmehar** [comment]
I cannot provide error message because we RUN AllPro 4.7 on eggdrops ipv6 it got disconnect.
I can write seprate issues.

**Comment by sirfz** [comment]
Thanks I'll look at them when I have the time and let you know of any updates for you to test :+1:

**Comment by fahadmehar** [comment]
Thanks :+1:
