### ISSUE TITLE
Problem setting Anti-Spam.

### ISSUE THREAD

**Issue by fahadmehar** [sirfz/allprotection#6]
Hello, 

I Enable     .chanset #channel ap:antispam - + 10 10 

Also did some editing in script.

``` tcl
# AntiSpamBot basic settings
# You can edit all these settings as you wish
# example: set antispam(nick) AntiSpamBot
set antispam(AntiSpam) $::altnick
set antispam(AntiSpamBot) ${::altnick}1
# Antispam ident & real name
set antispam(user) AP
set antispam(realname) "AllProtection Anti-Spam" 
```
# 

I Know only this much, How bot will come to channel do I have to do these all settings in script or i have to put any other command other then .chanset #channel ap:antispam - + 10 10 ?

Please guide me. Thanks.

**Comment by sirfz** [comment]
``` tcl
# Use: .chanset #channel ap:antispam + <greet> <cycle-time> <idle-time> (to enable)
# the antispam bot will not cycle a channel where last join occured in <idle-time> or more minutes.
# <greet> is either + or - which will enable or disable the on-join message.
# set default value here:
lappend ap:udefs {ap:antispam "- + 10 10"}
```

It clearly says, in the first line, that the first parameter is the enable/disable switch (+ to enable). So the correct command is (which is similar to all other protections):

```
.chanset #channel ap:antispam + + 10 10
```

Please carefully read the documentation before posting here.
