### ISSUE TITLE
Few bugs in All Protection (REMOTE)

### ISSUE THREAD

**Issue by fahadmehar** [sirfz/allprotection#7]
Hello ! I recently put ALL PROTECTION (Remote) on my Simple mIRC 
I face 2 problems... 

1: I cannot change the kick message. 

2: Why the Remote Sets my nick -R every-time as i always sets my nickname to this mode /mode Fahad +CR 

overall I like the All Protection remote... Please help me to fix these two problems.

**Comment by sirfz** [comment]
I'm not sure what you mean by "Remote". AllProtection is an Eggdrop script and not mIRC so you might be talking about something completely unrelated. To answer your first question:

You can modify the kick message via the [`kckcount(form)` variable](https://github.com/sirfz/allprotection.tcl/blob/master/allprotection.tcl#L238).

**Comment by fahadmehar** [comment]
That was a addon maybe you didn't wrote that addon. 

AllProtection.mrc is an addons that has complete channel protection. 
It protects your channels and 'you' from any kind of floods and spam.
* This script is "translation" of AllProtection.tcl by Sir_Fz. *

**Comment by sirfz** [comment]
Indeed, this is unrelated to allprotection.tcl
