### ISSUE TITLE
Why am I getting this error?

### ISSUE THREAD

**Issue by Landslyde01** [sirfz/allprotection#8]
`<Stryker> [17:01:02] Tcl error [bcpro:chans]: can't read "bcp(whois)": no such element in array`

It lists abt 20 of those at once. This just occurred when i set a sticky ban. Any ideas?

**Comment by sirfz** [comment]
Hello, this is coming from a different script (bcp?). `bcp` is not a variable used in AllProtection (neither is `bcpro:chans`).

**Comment by Landslyde01** [comment]
I hate that. I was sure I commented that script out. I wasn't sure if I wanted to use AP again, so I tried out another for bad channel prot. Went back to AP and left the other script running...by mistake. Thanks for the heads up. Your script is nice, sirfz. Excellent channel protection.
